# -*- coding: utf-8 -*-
"""Mosaddeq107Fibonacci.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19zxhtB-BpA3x6B9-_e7pN9NQH29pQTmd
"""

def fibonacci(n):
    a, b = 0, 1
    for i in range(n):
        a, b = b, a + b
    return a


def main():
    n = int(input("Enter the number of terms: "))
    print("The Fibonacci series is:")
    for i in range(n):
        print(fibonacci(i))


if __name__ == "__main__":
    main()