# -*- coding: utf-8 -*-
"""Mosaddeq107Fibonacci.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19zxhtB-BpA3x6B9-_e7pN9NQH29pQTmd
"""

def fibonacci(n):
    a, b = 0, 1
    for i in range(n):
        a, b = b, a + b
    return a


def main():
    n = int(input("Enter the number of terms: "))
    print("The Fibonacci series is:")
    for i in range(n):
        print(fibonacci(i))


if __name__ == "__main__":
    main()

"""



##Clarification of the code:
This code first defines a function called fibonacci() that takes an integer n as input and returns the nth Fibonacci number. 
The function works by initializing two variables a and b to 0 and 1, respectively. Then, it uses a for loop to iterate from 0 to n. 
In each iteration, the function assigns the value of b to a and then assigns the value of a + b to b. This effectively calculates the next 
Fibonacci number in the series. Finally, the function returns the value of a.

The main function prompts the user to enter the number of terms and then calls the fibonacci() function to print the Fibonacci series 
up to that number of terms."""

